---
- name: Listen for events on a webhook
  hosts: localhost

  ## Source event
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 7000
      filters:
        - ansible.eda.json_filter:
            include_keys: ['Host']
            exclude_keys: ['Content-Type','Content-Length','Accept']
        - ansible.eda.dashes_to_underscores:

  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.payload.message == "Aloha"
      actions: 
      - print_event:
          pretty: true
